### ISSUE TITLE
Fixed Footer

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/theme#106]
Is it possible to create a footer , something equivalent to this in css:

footer {
z-index:2000;
position: fixed;
}

I ask because I am not seeing anything that indicate fixed position in the css guide: http://docs.nativescript.org/angular/ui/styling.html#introduction. Can the same thing be accomplished another way.

**Comment by bradmartin** [comment]
Hi @leocrawf something like a fixed footer should be handled in your layout and it's actually really easy with NativeScript 😄 

``` xml
<GridLayout rows="auto, *, auto">
     <Label row="0" text="header" />
     <ScrollView row="1">
            /// whatever in here will scroll
      </ScrollView>
     <StackLayout row="2"> /// fixed footer <<<<
         //// whatever fixed in here
      </StackLayout>
</GridLayout>
```

The key is the main grid layout with the second row (index of 1) in the middle with a scrollview. This will scroll the layout in that row while keeping the first row (index 0) and third row (index 2) fixed in that main grid. Sorry if that sounds a little confusing but it should work. Might need a little tweaking, coding without an editor right now.

**Comment by leocrawf** [comment]
Thank you. This is easier than I thought.

**Comment by bradmartin** [comment]
:) glad it helped. Once you pick up layouts you'll feel like a Jedi Master
with NativeScript and personally I don't feel it's too difficult once you
understand a grid layout, my favorite layout.

**Comment by NathanWalker** [comment]
Thanks @bradmartin that was precisely it. @leocrawf hope you're enjoying NativeScript layouts... a lot of us find they are even more precise and easier to work with than HTML DOM markup.
