### ISSUE TITLE
Correct rule for text-primary?

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#117]
In utilities/text, I see text-primary defined as follows:

`.text-primary{
    color: $accent;
}`

Just wondering if that's by design - or should it be $primary

**Comment by NathanWalker** [comment]
Good question. It was by design actually.
It's similar to how btn-primary is an action button but changes color to match the accent of any skin for instance.

text-primary could be used to make a formatted label appear like a hyperlink but it would use whichever the accent color is according to the skin you're using, light, dark, sky, etc.

If you find it confusing we could reconsider but I think bootstrap follows a similar pattern.

**Comment by erjdriver** [comment]
I think if the class name is text-primary - it seems to me that it should be tied to $primary color.

maybe text-accent or text-hyperlinked could be tied to $accent.

Not a big deal - because I can override it easily with the excellent setup design.

btw, I noticed that when I tap on a link (e.g. a side-drawer entry) - there's no visual feedback. any way to enable that?

Also, any doc on advanced SASS or at least the features supported by the plug-in would be great - e.g. if statements etc.
