### ISSUE TITLE
.input-rounded cuts off hint and text

### ISSUE THREAD

**Issue by vcooley** [NativeScript/theme#133]
I am running into an issue where my hint and text in input fields is cut off in iOS and to a smaller extent Android with the `input-rounded` class.

iOS
![image](https://cloud.githubusercontent.com/assets/12551141/25103100/d5d4cd32-2380-11e7-9f7a-5433626b2a15.png)

Android
![image](https://cloud.githubusercontent.com/assets/12551141/25103105/de2f6d02-2380-11e7-9e33-5f091ecc3ae2.png)

```
<StackLayout class="form login-form">
    <StackLayout class="input-field">
            <TextField
              class="input input-rounded"
              hint="Email"
              keyboardType="email"
              autocapitalizationType="none"
              [(ngModel)]="user.email"></TextField>
    </StackLayout>
</StackLayout>
```

In app.css I am importing the light theme like this: 
`@import 'nativescript-theme-core/css/core.light.css';`

**Comment by NathanWalker** [comment]
@vcooley Try removing the surrounding `input-field`:
* Either remove `input-field` class on stack surrounding it or...
* Remove the extra stack entirely

**Comment by vcooley** [comment]
@NathanWalker That worked nicely, thanks.

Not sure whether this is a bug or intended behavior. If it's not a bug, the documentation at https://docs.nativescript.org/angular/ui/theme.html#forms may need to be updated.

Currently, there is an example that is formatted similar to the code in my original post.

**Comment by NathanWalker** [comment]
Thanks @vcooley you are correct.
@tjvantoll when you get a chance, if you could update the docs to reflect well for these particular styles:
https://github.com/NativeScript/theme/blob/master/app/pages/forms.xml#L30-L36
Note they should not be wrapped in a layout container classed with `input-field` since they are standalone form inputs without adornments. The `input-field` class on a layout container surrounding inputs is only needed for the adornments displayed in the demo app as seen for only these setups:
https://github.com/NativeScript/theme/blob/master/app/pages/forms.xml#L13-L28

**Comment by tjvantoll** [comment]
Oh hey, I learned something new!

@NathanWalker Can you give https://github.com/NativeScript/docs/pull/739 a quick review for me?
