### ISSUE TITLE
Root classes not applied with theme 2.0

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#172]
Hey 🙂 

I’m trying out the 2.0 theme in a new app and I’m having trouble with the root class names—specifically, even after including `import "nativescript-theme-core";` I don’t have the `ns-root` or `ns-ios` or `ns-android` class names.

![Screen Shot 2019-08-26 at 2 18 07 PM](https://user-images.githubusercontent.com/544280/63712874-8d761680-c80c-11e9-9785-4dee922b200e.png)

Steps to reproduce.

```
tns create MyApp --ng
tns plugin update nativescript-theme-core
```

Add the following line to the top of your `app.component.ts` file.

``` TypeScript
import "nativescript-theme-core";
```

Then run your app with `tns debug android`. In the DevTools I do not see the root class names.

Any help would be appreciated. Thanks!

**Comment by bundyo** [comment]
The root classes are applied on the rootView, which in you case is probably the Frame. Since Frame is not visible in DevTools, try getting the className of application.getRootView() and see if they are there?

**Comment by Jonatthu** [comment]
When I am trying to apply .ns-dark & {} on a component is not working since the root view is not there, Is there any way to include this classes in all the levels of the components? I am using page-router-outlet and inside of this one I am using a router-outlet so this root classes will not take any effect on sub nested components
