### ISSUE TITLE
Migrating to theme 2.0

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#178]
I installed theme 2.0 - migrating my app to NS 6.1.

`npm i nativescript-theme-core --save`

I also installed 

`npm i sass --save-dev`

What else do I need to install?

Do I need node-sass?

Is there an app template that I can create - to see how a client app uses 2.0?

In the _app-variables.scss file - how do I start with a dark theme

`@import "~nativescript-theme-core/core";`

I've got above now - which seems to default to light theme.

Thanks.

**Comment by bundyo** [comment]
Check out the README on the front page of this repo, I think everything is explained there. You can use either node-sass or sass (which was dart-sass before).

There are currently no templates yet available - official {N} templates are planned to transition to Theme 2.x in {N} 6.2. You can check out the app included in this repo as a sample.

**Comment by erjdriver** [comment]
I did read it but I'll do it again.

Looking at the package.json file - I see

`"sass": "1.22.12",
 "sass-lint": "1.13.1",
"sass-loader": "8.0.0",`

I just have sass. How do I get the other two or are they not required.

I'm using scss/sass.

The app seems to load the default app.scss - which has a light theme. Where does this happen? What if I'd like to set the theme programatically to something before the app is initialized.

Also, how do I override some light and dark theme variables.

Thank you.

**Comment by bundyo** [comment]
* Since you're using Webpack, you should have at least sass-loader specified in your Webpack config. And since nativescript-dev-webpack has 7.1.0 as a dependency, you don't need to add it in your app, unless you want a different version. 7.1.0 is fine - it was the first version to add support for the `implementation` config option. So you only need to add [this](https://github.com/NativeScript/theme#should-i-use-sass-or-node-sass) to your webpack config. Sass-lint is for linting your SASS code, so it is not required. The Theme is using it in CI.

* The light mode is default - you don't need to add `.ns-light` to the root element to get it. Adding `.ns-dark` to your root element will change your app to dark mode - you can add it directly to your root view markup. Using the API to change the mode will also work even if the app has not yet started.

* Why do you need separate files? Webpack will need to load both files anyway if you plan to allow changing the mode by the user.

* Internally Theme 2.x uses 2 SASS maps for light and dark colors. Can you list which colors do you want to change?

* In order to import just the Theme variables in one of your modules, add this import:
```scss
@import "~nativescript-theme-core/scss/variables";
```
It will import just the variables and mixins, without any additional styling. Also check [this](https://github.com/NativeScript/theme#using-theme-variables) for how to use them. Currently the available variables are not listed, you can check them in [this folder](https://github.com/NativeScript/theme/tree/master/src/scss/core/colors). I'll make sure to list all the variables in the README.

**Comment by bundyo** [comment]
Oops, triggered the bot.

Do continue in the closed issue.
