### ISSUE TITLE
[IOS 13] - Cannot apply Light mode on application when device is Dark mode

### ISSUE THREAD

**Issue by fvdung** [NativeScript/theme#202]
as the title, I cannot apply light mode for app on IOS 13 when device is Dark mode.
But device is Light, my app can apply both mode (Dark & Light)

**Comment by bundyo** [comment]
I think this is a limitation of how dark mode is handled. @vchimev, can you chime in here?

**Comment by bundyo** [comment]
Currently the Theme API can't change to Light mode in iOS if Dark mode has been by the system. The Theme API simply removes the .ns-dark class  from the root view and replaces it with .ns-light. However, in order to get the changes applied, it does this through className, while I think .ns-dark set by the OS is only set in cssClasses and restored after className is set, right?

**Comment by fvdung** [comment]
was available in {N} 6.2.0
