### ISSUE TITLE
V2 Optimization Issue when Webpack Mode Production

### ISSUE THREAD

**Issue by logitron** [NativeScript/theme#234]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.2.2 version and is up to date.
✔ Component tns-core-modules has 6.2.3 version and is up to date.
✔ Component tns-android has 6.2.0 version and is up to date.
✔ Component tns-ios has 6.2.0 version and is up to date.

**Describe the bug**
When building a release version of the application for iOS, I noticed that I was getting this message:
`CONSOLE ERROR file:///node_modules/@nativescript/core/trace/trace.js:174:30: Error: Css styling failed: Error: undefined:11:16959: property missing ':'`.  There are also several visual css problems with the app.

Upon further investigation, I isolated the issue as a result of some sort of optimization that webpack is doing in 'production' mode as it relates to this file:
`https://github.com/NativeScript/theme/blob/master/src/scss/core/colors/_index.scss`

Specifically, it has to do with the `transparent: transparent` setting within the `$color` variable.  Whatever webpack optimization doesn't like that.  I noticed that changing it to `transparent: rgba(0, 0, 0, 0)` causes everything to work properly.

I tried to do as much due diligence as I could to isolate the exact issue and cause.  Please let me know if there is any more information I can provide or anything I can do to help.  Thanks!

**Comment by bundyo** [comment]
Thanks, I'll investigate it as soon as I get my laptop working again (firmware update issue).

**Comment by samc36** [comment]
I can confirm that I'm seeing the same problem. I couldn't understand why I couldn't build but had isolated the problem to be located in my: `@import '~@nativescript/theme/index';` import.

Package.json:
`{
  "name": "my-project",
  "version": "1.0.0",
  "description": "My Project",
  "author": "My Company <hello@mycompany.ie>",
  "license": "MIT",
  "nativescript": {
    "id": "org.mycompany.project",
    "tns-ios": {
      "version": "6.3.0"
    },
    "tns-android": {
      "version": "6.3.1"
    }
  },
  "dependencies": {
    "@nativescript/core": "^6.4.0",
    "@nativescript/theme": "^2.3.0",
    "axios": "^0.19.2",
    "base-64": "^0.1.0",
    "moment": "^2.24.0",
    "nativescript-couchbase-plugin": "^0.9.6",
    "nativescript-socket.io": "^0.11.1",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-sidedrawer": "8.0.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-windowed-modal": "^6.2.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "babel-loader": "^8.0.6",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "^1.0.1",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "1.5.0",
    "nativescript-vue-template-compiler": "^2.4.0",
    "nativescript-worker-loader": "^0.10.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.3.1",
    "terser-webpack-plugin": "^1.4.3",
    "vue-loader": "^15.8.3",
    "webpack": "^4.41.6",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.3.10"
  }
}`

Running node: v12.15.0
Running npm: v6.13.4

OS: Mac OS Mojave v10.14.6 (18G95)

In my case, I'm building for android, and in both sidekick and terminal it appears to be failing here:
`WARNING in ./app.scss
Module build failed (from ../node_modules/nativescript-dev-webpack/css2json-loader.js):
Error: undefined:1:46030: property missing ':'
    at error (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:62:15)
    at declaration (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:223:33)
    at declarations (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:252:19)
    at rule (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:560:21)
    at rules (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/node_modules/css/lib/parse/index.js:564:20)
    at Object.loader (/Users/user/Projects/_Web/my-project/node_modules/nativescript-dev-webpack/css2json-loader.js:12:23)
 @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$) ./app.scss
 @ ./main.js` 

It will build in terminal and exports with broken styles, and in sidekick it will not build due to some issues with the snapshot due to the bad .css file. `Build failed. Executing webpack failed with exit code 2.`

I can build perfectly fine if I don't include `@import '~@nativescript/theme/index';` but then I can't run the theme the way I want, and this project just needed to be built and I don't want to re-style parts of the app. Project worked perfectly fine when built without the release flag, or when it was running in an emulator.

In my particular case, the only lines I could find with empty properties were in all of the theme.css files where `--const-border-radius: ;` is blank in all of them. Changing it didn't help me. 

I've also noted that if I include any of the scss theme files e.g. `@import "~@nativescript/theme/forest.css";`

In every case, I've been able to trace it back to the same particular line as logitron. If I use my custom theme overrides and then include index like this: `@import '~@nativescript/theme/index';` and then modify theme/scss/core/colors/_index.scss so that transparent isn't listed in the $colors map, it will work, I can't even get it to work by changing it to `rgba(0,0,0,0),`

**Comment by MihkelBaranov** [comment]
Experiencing the same issue on android 
Node: v12.6.0,
npm: 6.9.0
tns: 6.4.0


package.json
```json
{
	"nativescript": {
		"id": "org.nativescript.TestApp",
		"tns-android": {
			"version": "6.4.1"
		},
		"tns-ios": {
			"version": "6.4.0"
		}
	},
	"main": "app.js",
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"repository": "<fill-your-repository-here>",
	"dependencies": {
		"@nativescript/theme": "~2.3.0",
		"@nstudio/nativescript-pulltorefresh": "^1.1.1",
		"nativescript-audio": "^5.0.5",
		"nativescript-image": "^3.0.1",
		"nativescript-material-bottomsheet": "^3.1.7",
		"nativescript-material-button": "^3.1.7",
		"nativescript-material-cardview": "^3.1.7",
		"nativescript-material-dialogs": "^3.1.7",
		"nativescript-material-snackbar": "^3.1.7",
		"nativescript-perms": "^2.0.3",
		"tns-core-modules": "~6.4.0"
	},
	"devDependencies": {
		"nativescript-dev-webpack": "~1.5.0",
		"node-sass": "^4.13.1",
		"sass-loader": "^8.0.2",
		"tns-platform-declarations": "^6.4.1",
		"typescript": "~3.5.3"
	},
	"gitHead": "d8bdf0799a219051f28f8abd7c258d2bf2fce6e1",
	"readme": "NativeScript Application"
}

```

app.scss
```scss
@import "~@nativescript/theme/core";
@import "~@nativescript/theme/default";
```

log
```
JS: Error: Could not load CSS from app.css: Error: Module build failed (from ../node_modules/nativescript-dev-webpack/css2json-loader.js):
JS: Error: undefined:11:14273: property missing ':'
JS:     at error (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:62:15)
JS:     at declaration (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:223:33)
JS:     at declarations (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:252:19)
JS:     at rule (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:560:21)
JS:     at rules (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:117:70)
JS:     at stylesheet (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:81:21)
JS:     at Object.module.exports [as parse] (/Users/mihkel/Projects/test/TestApp/node_modules/css/lib/parse/index.js:564:20)
JS:     at Object.loader (/Users/mihkel/Projects/test/TestApp/node_modules/nativescript-dev-webpack/css2json-loader.js:12:23)
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
```

**Comment by bundyo** [comment]
Seems to be an issue with node-sass. Investigating.
