### ISSUE TITLE
Tabs - need images for some layouts

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#44]
@sitefinitysteve @myninka

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/NativeScript/issues/1217

**Comment by sitefinitysteve** [comment]
Okay so per @enchev we can't do the tabstrips as mocked up
https://github.com/NativeScript/NativeScript/issues/1217

Icon fonts can't be used above\below the text, only physical images... so I'm not sure what to do here, we could ship a whole set of the blue accent ones, but then if someone changes their accent color, the icons are all off... maybe just ship whites or something?  Because it's every icon at every dpi, adds up.

I would love to stick to icon fonts, but not sure how to finagle this one outside of blue accent color images for the demo app, and then just tell the user to make their own to use in their app?

**Comment by NathanWalker** [comment]
Just shipping with white icon images will be great as we can use tintcolor api which is coming with new tns-core-modules.

**Comment by myninka** [comment]
Hey
As I understood you will need the images only for demo purposes - we don't need to ship them with the theme, just provide the right mechanism for the user so if they set tab bar with images everything to be as designed. Am I on a right track here?
In that case you can us always the Material icon set:
http://www.google.com/design/icons/
Choose icon, color, size, even file format and download it. For the tab bar the size is 24dp. Google have great tools!

**Comment by prantikv** [comment]
Any news on this..unable to implement icons in tabView using fontAwesome


```
<TabView>
    <StackLayout *tabItem="{title: '&#xf015; Profile &#xf1e0;" >
   <Label class="fa" text="&#xf015;"></Label>
<Button class="fa" id="button" text="&#xf1e0; Tap me!" ></Button>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf015; Stats">
        <Label text="Second tab item"></Label>
    </StackLayout>
 
    <StackLayout *tabItem="{title: 'Settings'}">
        <Label text="Third tab item"></Label>
    </StackLayout>
</TabView>
```

I have fontawesome set as `font-family` in my `app.css`

**Comment by prantikv** [comment]
is there a way to get badges for Tabs..


![get_thumbnail2](https://cloud.githubusercontent.com/assets/5754101/20743852/8ff67386-b6fe-11e6-82a7-68b6031f2956.jpg)
