### ISSUE TITLE
TNS CLI Limitations / Distribution of themes

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/theme#5]
If you want to distribute the themes afterwords; the current TNS cli system template require a fixed structure; I have already added TNS issue in here: https://github.com/NativeScript/nativescript-cli/issues/1945 related to this issue.  

Maybe both of these need to be linked as the "cleanTemplate" flag would solve both issues.

**Comment by tjvantoll** [comment]
The (tentative) plan is to distribute the theme as an npm module, which you could then import via `import` in a CSS file.

The default templates would depend on the main theme by default, so `tns create foo` would automatically have the theme applied, but you could do things manually if you’d like.

```
tns create foo
cd foo
npm install tns-theme-core
```

``` css
/* app.css */
import { url('tns-theme-core/theme.css') }
```

I’m curious what you think of that approach.

**Comment by NathanaelA** [comment]
Lets pretend I create an awesome theme called lightWave (tns-theme-lightwave);
My theme folder structure is:
```
lightWave.css
fonts\CoolFont.ttf
images\Name.png
images\Name@2x.png
images\Name@3x.png
images\Name@4x.png
app_resources\android\drawable\coolGradient.xml
```

If I use NPM to install this; do you know what is going to happen?   ;-)

I get:
/project/node_modules/tns-theme-lightwave with the above directory structure.
I DO NOT get any of the images built in as resources, and EVERYTHING has to be referenced from /tns-modules/tns-theme-lightwave, the css can't actually access images properly since they aren't resources (\*).   The end user has no ability to "customize" any of the theme elements easily.   The user has to manually/Programmatically register each of the fonts in both iOS and Android.  In addition any thing dropped in the app_resource/ will be worthless as they won't be built in as resources...  
(Not 100% sure on this, but webpacking may also skip some of the resources, so you might not even get them...)  
(\* - the resolution independence on images occurs only on compiled resources in Android and quite possibly only on resources in iOS also)

In my humble opinion; this makes a straight npm install option a complete royal pain and in most cases a total non-starter as ALL the support files for the most part will be useless...

What we need to happen is upon install:
- lightwave.css moved to /app/themes/lightwave
- coolFont.ttf moved to /app/fonts
- images/name.png moved to /app/app_resources/ios  &  /app/app_resource/android/drawable-mdpi
- images/name@2x.png copied to /app/app_resource/ios
- images/name@2x.png renamed to name.png and moved to /app/app_resource/android/drawable-xhdpi
- images/name@3x.png copied to /app/app_resource/ios
- images/name@3x.png renamed to name.png and moved to /app/app_resource/android/drawable-xxhdpi
- images/name@4x.png copied to /app/app_resource/ios
- images/name@4x.png renamed to name.png and moved to /app/app_resource/android/drawable-xxxhdpi
- Anything put into /app_resources/ directly is copied as is to /app/app_resource

Now your choices are to fix this issue:
1. We create a custom npm post install script; this script has to be _included_ with every theme, to automatically move everything around like I propose above.   
2. We make tns smart enough to do the above.

So now you understand why I was recommending we make tns smart enough to handle this; it is one less item that a theme author has to remember to add to his theme.    However, on the flip side having it as a post-install script does allow the script to be easily iterated as new features are discovered to be needed, where getting changes done to TNS seems to require all the planets to be in alignment and a sacrifice to appease the gods...     ;-)

The code to activate/use a theme is simple:
```js
/* app.css - fixed theme */
import { url('themes/lightwave/lightWave.css`);

/* OR */

/* app.js - ability to dynamically set themes */
var theme = require('nativescript-themes');
theme.applyTheme('themes/lightwave/lightWave.css');
```

** please note -- my ns-themes doesn't YET have "themes/" as a default search location; but it could be easily changed to have the following work:
```
theme.applyTheme('lightwave');
```

**Comment by tjvantoll** [comment]
@NathanaelA Ok this makes a lot of sense, thanks for the thorough explanation. I actually do like the idea of having this start as a hook. Because changing `tns` does indeed take some effort, and also because I think it’s important for us to be able to iterate quickly until we decide on a format that works.

For the moment we’ll either need to write a hook, or plan on packing up this theme’s assets as part of the default app template instead of distributing via npm—until we can sort all this out.

**Comment by vakrilov** [comment]
To continue the discussion on the distribution - I think that the best case is to be able to use the theme in both CSS and SCSS.
Using the SCSS directly will give you:

-  Ability to customize the theme variables (similar to [boothstrap](https://github.com/twbs/bootstrap-sass#sass-1))
- Further improve the the "share code between web and mobile" scenario. In pure form CSS is not sharable. However, with SCSS you can use common `_variables.scss` for web and {N} where you can define colors, fonts etc.

## Using CSS
I think the cleanest approach is to have some kind of `npm build-css` task what you can run after you instal the `npm package` that will build the theme and copy the image/font resources inside your app. 

## Using SCSS
Two ways to go here
### With `nativescript-dev-sass` plugin
I've done a PR for the sass-plugin (toddanglin/nativescript-dev-sass#7) that will allow you to import `scss` files directly form `node_modules`. So the way I see it will be

- `npm install  tns-theme-core`
- modify you app.scss to import the theme (e.x. `@import tns-theme-core\themes\light`)
- customize the theme variables before the import (we should make sure we define all variables in the theme with `!default` to support that)

In the case we need a npm task to copy the  image/fonts resources in the app. It can also add a `_variables.scss` file in your app with all varialbes commented so that you can easily start customizing.

### With webpack
Distribute a `webpack.config` file with build task that uses it.  If you are already using webpack - you can integrate that in your current setup. 

Not sure if we can handle the resources with webpack as well.

**Comment by tjvantoll** [comment]
@vakrilov: Big 👍  from me on your ideas on working with theme in SASS and the PR.

One trivial question: if we’re publishing two different things to npm what would we call each? `tns-theme-core` and `tns-theme-core-source`?

**Comment by NathanaelA** [comment]
Instead of two things; there is no reason why the plugin post-install script couldn't install both a pre-processed .css and the scss files.

**Comment by NathanWalker** [comment]
I agree. Nathanael and I have both worked together on nice postinstall
scripts for other things and could see that working very nicely here.

**Comment by hdeshev** [comment]
AFAIK the plan is to publish both in the same package the way Kendo themes work now. E.g. 

- node_modules/nativescript-default-theme/.../_buttons.scss
- node_modules/nativescript-default-theme/**dist**/theme.dark.css
