### ISSUE TITLE
Android BottomBar?

### ISSUE THREAD

**Issue by James-Parsons** [NativeScript/theme#88]
Earlier this year, Google updated the material design spec to utilize bottom navigation tabs as opposed to tabs on the top. Is there any chance e will see that reflected in the NativeScript theme?

**Comment by bradmartin** [comment]
I don't make the call on this, but @James-Parsons I don't imagine a view component will make it into the 'theme' project since this is all about styling. I did start a plugin for the bottom bar component for Android months ago, just never finished it. https://github.com/bradmartin/nativescript-bottomnavigation It didn't need much more to get going but wasn't much interest so I let it slide. 

I might get around to finishing it up in the next few weeks.

**Comment by NathanWalker** [comment]
@bradmartin thanks. 👍  yes indeed @James-Parsons that is correct. Best to utilize a plugin as mentioned for something like that.
