### ISSUE TITLE
Ripple effect is no more

### ISSUE THREAD

**Issue by aboalwi** [NativeScript/theme#94]
Go to buttons page... click em all ... no ripple effect. :/

**Comment by bradmartin** [comment]
@NathanWalker fairly certain this occurs with a combination of styles on android buttons. Specifically `border-radius, border-width, and background-color`. Without testing I'm leaning toward the `border-radius` throwing it off but I forget 😄

**Comment by bradmartin** [comment]
This usually happens with border radius, background color, and maybe border
width all being set. Usually removing the border radius will fix the
android button. Just fyi Nathan

**Comment by TheOriginalJosh** [comment]
@bradmartin is this issue on the NativeScript teams radar? it seems like it should be since border-radius is a big part of the design.

**Comment by bradmartin** [comment]
I don't even know if this is logged as an issue anywhere for the core team. It probably goes unnoticed for most people to be honest. Because it might be a combination of the different styles. I really don't recall but I do know I encountered it the other day and had to remove the background or border-radius to get it working again. If I come across it again I'll let you know for sure.

**Comment by sitefinitysteve** [comment]
Its such a small thing, but it's so big... it's like this level of polish on Android that you dont know you need\want until it's just not there.  It's what seperates us from the Hybrids :)

**Comment by TheOriginalJosh** [comment]
To be honest, I hadn't noticed it at all.

**Comment by bradmartin** [comment]
I notice it but that's my android fan boy coming out :)

**Comment by sitefinitysteve** [comment]
We'll start to call you Brandroid Martin 👍 (tm)

**Comment by bradmartin** [comment]
`border-width: 1` is the culprit.
